# Generated by Django 2.2.1 on 2019-09-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(default='', max_length=35, unique=True)),
                ('mix_type', models.CharField(default='', max_length=16)),
                ('normalization', models.CharField(default='', max_length=30)),
                ('season', models.CharField(default='', max_length=6)),
                ('location', models.CharField(default='', max_length=30)),
                ('model_img_url', models.CharField(default='', max_length=150)),
            ],
            options={
                'ordering': ['-location'],
            },
        ),
    ]
