# Generated by Django 2.2.1 on 2019-09-05 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plot_viewer', '0002_plot_model_img_url1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='model_img_url1',
        ),
    ]
