# Generated by Django 2.2.1 on 2019-10-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot_viewer', '0003_remove_plot_model_img_url1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='image_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
