# Generated by Django 2.2.1 on 2019-10-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot_viewer', '0004_auto_20191001_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='csv_url',
            field=models.CharField(default='', max_length=150),
        ),
    ]
